### ISSUE TITLE
Impersonator on discord

### ISSUE THREAD

**Issue by borntohonk** [jimzrt/Incognito_RCM#11]
ahzee#2237
discord id 381948099494412301

There's been a guy posing as you on discord, his previous nickname was jimzrt and had the same profile picture as you.

**Comment by borntohonk** [comment]
![image](https://user-images.githubusercontent.com/6264306/71779901-8bdb0d00-2fbb-11ea-9906-9a26670d2cbd.png)
![image](https://user-images.githubusercontent.com/6264306/71779902-8f6e9400-2fbb-11ea-9b50-d6cf1e2cfa9b.png)

**Comment by jimzrt** [comment]
yeah, he even made a reddit and second github (jimzrt2) account...
he admitted it in the end. really strange.
 
![impersonator](https://user-images.githubusercontent.com/19434859/71782121-ec2b7800-2fd6-11ea-88ea-b8089982211c.png)

thanks for calling attention to it!
