### ISSUE TITLE
v0.6.0 seems to have the same bug as in v0.5.0

### ISSUE THREAD

**Issue by muxi1** [jimzrt/Incognito_RCM#12]
I tried to perform a restore in emuMMC under v0.6.0, but after that Incognito was still active.
It seems to be the same bug that already existed in version 0.5.0 and has been reported here:
https://github.com/jimzrt/Incognito_RCM/issues/9

**Comment by jimzrt** [comment]
thanks for the report, can you try again with v0.6.1?
[https://github.com/jimzrt/Incognito_RCM/releases/tag/v0.6.1](https://github.com/jimzrt/Incognito_RCM/releases/tag/v0.6.1)

**Comment by muxi1** [comment]
The problem is fixed with v0.6.1.
