### ISSUE TITLE
"Validate...Error!"

### ISSUE THREAD

**Issue by DarthAK47** [jimzrt/Incognito_RCM#14]
When attempting to use any function of Incognito_RCM, after successfully obtaining my keys, I get this "Validate...Error!". 

Switch v9.1.0 running Atmosphere 10.2
![Validate_Error](https://user-images.githubusercontent.com/59671075/72024117-a83cab00-3242-11ea-9860-a65d14f92798.jpg)

**Comment by borntohonk** [comment]
latest version is 0.6.1, not 0.5.1 @DarthAK47

**Comment by DarthAK47** [comment]
> latest version is 0.6.1, not 0.5.1 @DarthAK47

The picture I uploaded was accidentally chosen instead of the picture using 0.6.1.
Using 0.6.1 causes the exact same "Validate...Error!" message to appear when trying to use any function of Incognito_RCM.

**Comment by borntohonk** [comment]
@DarthAK47 I can only guess, but that means your boot0 or prodinfo are fucked

**Comment by DarthAK47** [comment]
@borntohonk Any idea how to fix it?

**Comment by borntohonk** [comment]
@DarthAK47 fix your own console? Only you can do that.

**Comment by DarthAK47** [comment]
@borntohonk Wow, aren't you so helpful.
I was asking if whatever you said could be fixed... not can you fix it for me but OK.

**Comment by borntohonk** [comment]
@DarthAK47 i'm saying this is an issue unique to you, your setup is broken.

**Comment by jimzrt** [comment]
@DarthAK47 
sorry for the late reply - can you boot into Atmosphere? And do you have a valid serial number under settings?
In the validating step the first 4 bytes of prodinfo are read and decrypted.
If those bytes do not match the "magic" identifier (CAL0) for this partition, this error shows up.
But like @borntohonk said, either key derivation failed or your prodinfo partition is corrupted (but then you shouldn't be able to boot into atmosphere).
Closing this because it seems to be unique to your setup, but feel free to comment.

**Comment by Hawods** [comment]
@jimzrt My ns can boot into kosmos but got the same error when I try to backup or incognito. My real system version is 6.1. I tried to update the system to 8.1 or 9.0.1 or 9.1, all got the same error. Also tried emuMMC, same error too.

**Comment by Hawods** [comment]
Btw, I'm using kosmos 15.1.

**Comment by Hawods** [comment]
@jimzrt What's mean "first 4 bytes of prodinfo do not match the "magic" identifier (CAL0)"? How is this happen? And how may I fix this? I tried restore NAND, still not helped.

**Comment by deadair3210** [comment]
It means your prodinfo partition is hosed

**Comment by Hawods** [comment]
Does it mean the prodinfo was broken before I backup full NAND? But I can install and run games normally. So is that a problem?

**Comment by schmeichs** [comment]
Apologies, I have opened a new bug (possible in error) - lockpick_rcm has the same issue prior to v1.8.1 which addresses the case that PRODINFO keys are handled differently in newer consoles.  The PRODINFO in this case is likely intact but behaving slightly differently to older console versions
