### ISSUE TITLE
FW 9.1.0 incompatibility

### ISSUE THREAD

**Issue by muxi1** [jimzrt/Incognito_RCM#2]
Incognito_RCM does not run under FW 9.1.0

btw
would it be possible to add the payload chainloading option, as is the case with Lockpick_RCM?

**Comment by DitDitGitHub** [comment]
I'm getting this aswell

**Comment by borntohonk** [comment]
Confirmed to be an issue. Incompatible with new sept for 9.1.0

**Comment by evildude221** [comment]
Probably redundant, but I am having this issue as well. Does anyone know of a workaround?

**Comment by borntohonk** [comment]
https://github.com/jimzrt/Incognito_RCM/pull/3
proposed fix

@evildude221 I did a compile of the PR I've submitted and it works for 9.1.0.

There's a release attached in my fork.

**Comment by evildude221** [comment]
@borntohonk Awesome!

**Comment by brlala** [comment]
> #5
> proposed fix
> @jimzrt
> 
> @evildude221 I did a compile of the PR I've submitted and it works for 9.1.0.
> 
> There's a release attached in my fork.

thanks! can confirm it's working. Is it possible to make it such that it's future fool proof? like changing the max version to version 15 or version 20?
