### ISSUE TITLE
unknown rcm pkg1 version

### ISSUE THREAD

**Issue by acidpancake** [jimzrt/Incognito_RCM#32]
in the title...
Version 10.0.2

_Edit: Updated to 10.0.4 Still happens_

**Comment by Scandal-UK** [comment]
Try this version:
https://github.com/Scandal-UK/Incognito_RCM/releases

**Comment by acidpancake** [comment]
> Try this version:
> https://github.com/Scandal-UK/Incognito_RCM/releases

thanks!
