### ISSUE TITLE
Incognito rcm makes mistake

### ISSUE THREAD

**Issue by valelisa89** [jimzrt/Incognito_RCM#43]
when I enter incognito, rcm always makes a mistake
![Uploading IMG_20211214_071520.jpg…]()

**Comment by Masamune3210** [comment]
You didn't give time for your picture to upload so we didn't get the picture

**Comment by valelisa89** [comment]
![IMG_20211214_071520](https://user-images.githubusercontent.com/96103079/145951865-76b5be3b-9d8a-44f7-8480-395ba37b4b80.jpg)
sorry I was in a hurry anyway when I go undercover it gives me an error

**Comment by valelisa89** [comment]
sorry if the photo was wrong but I did it with the tablet

**Comment by Masamune3210** [comment]
Yeah....I can't read that. Just type what it says lol
