### ISSUE TITLE
Other services seem to be caching console-unique parts of PRODINFO

### ISSUE THREAD

**Issue by sttng** [jimzrt/Incognito_RCM#6]
Adubbz and SciresM said in ReSwitched once: we know that other services seem to be caching console-unique parts of PRODINFO and this was something that never really got looked into. 
Isn’t this worth investigating?

**Comment by borntohonk** [comment]
@sttng Old discussion, cannot be proved. Which is the core of the argument. It's a "what if scenario". And you're misinterpreting it. It's a "what if" nintendo caches it on their servers.

**Comment by jimzrt** [comment]
Sure is worth investigating, but this is outside of my realm.
I would just advise to apply incognito_rcm directly after factory reset so the fake data is cached instead.
