### ISSUE TITLE
Getting Unknown Pkg1 version error

### ISSUE THREAD

**Issue by Lightning-LH** [jimzrt/Incognito_RCM#7]
Hey,

Thanks for your great work.  I'm running atmosphere on fw 9.1.0 and when trying to run backup I always get Unknown Pkg1 version error.  Happens for both sysnand and emummc.  Any ideas what I can do to fix?  Thank you!

**Comment by Pikotaro** [comment]
same here

**Comment by FloDuno** [comment]
It's due to Incognito_RCM has not been released yet for the 9.1 update. We need to be patient and wait for next release

**Comment by Lightning-LH** [comment]
Ah my apologies, I thought it was compatible for 9.1 as I saw a 9.1 folder in the source

**Comment by jimzrt** [comment]
sorry, did have the source for a few days ready, but no release.
it is up now!
