### ISSUE TITLE
restore backup

### ISSUE THREAD

**Issue by Yuji6297** [jimzrt/Incognito_RCM#8]
Hi, when use Incognito_RCM on my sysnand, i lost serial number
when i restore backup, sysnand still not have have serial number

**Comment by jimzrt** [comment]
did you make a backup before applying incognito_rcm?

**Comment by Yuji6297** [comment]
yes, i backup then apply incognito

**Comment by jimzrt** [comment]
thats strange... keep the backup and try with latest version. And check if you have backups with .1 or .2 suffix and try renaming.
