### ISSUE TITLE
Serial number does not wipe on emuMMC

### ISSUE THREAD

**Issue by thedopefiend** [jimzrt/Incognito_RCM#9]
I am able to retrieve my prod info using the latest incognito rcm but whenever I try using incognito on my emuNAND the serial number can still be seen under serial information. On 9.0.1 the serial number was blank. Not sure if something has changed in the newer version or there is a real issue. I’m currently on 9.1.0.

**Comment by muxi1** [comment]
I can confirm that - but in reverse. According to Incognito_RCM the restore of an already existing prodinfo_emunand.bin is correctly processed, but after a reboot still no SN is displayed in the system settings under console.

AMS v0.10.1
emuMMC 9.1.0

**Comment by jimzrt** [comment]
thanks for the report, will investigate and remove latest release for now!

**Comment by muxi1** [comment]
Version 0.5.1 fixes this problem!

**Comment by jimzrt** [comment]
thanks for testing
